### ISSUE TITLE
Handling Cosmos Amino encoded data

### ISSUE THREAD

**Issue by zmanian** [iqlusioninc/sagan#3]
It seems like we could easily have event trigger queries in Sagan but they would largely be in opaque amino encoded bytes.

Amino should eventually be sufficiently protobuf compatible that we can have .proto files for the cosmos hub but probably not till cosmos-hub 4.

 Perhaps the approach we should take with Sagan is just storing the opaque bytes and leave it to some Golang code to decode the data.

**Comment by tony-iqlusion** [comment]
Not relevant after the migration to Protobufs
